[workspace]
channels = ["conda-forge"]
name = "mine-pytorch"
platforms = ["win-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://mirror.sjtu.edu.cn/pypi/web/simple/"
extra-index-urls = ["https://pypi.tuna.tsinghua.edu.cn/simple/", "https://pypi.mirrors.ustc.edu.cn/simple/", "https://pypi.org/simple", "https://pypi.org/simple2"]

[tasks]

[dependencies]
python = "3.13.*"
ipykernel = ">=6.16.2,<7"

[pypi-dependencies]
pytorch-lightning = ">=2.5.2, <3"
matplotlib = ">=3.10.5, <4"
torch = {version = "==2.7.1", index = "https://download.pytorch.org/whl/cu128"}
torchvision = {version = "==0.22.1", index = "https://download.pytorch.org/whl/cu128"}
scikit-learn = ">=1.7.1, <2"
pillow = ">=11.3.0, <12"
